config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
 
  resources :profiles do
   collection do
     get :view_profile
     get :search
     get :search_id  
     get :profile
     get :shortlisted
     get :viewed_profile
     get :register
     get :matches
     get :viewed_not_contacted
     get :create_profile
     get :add_profile_picture
     post :add_profile_picture
     get :send_accept_invite
     get :approve_invite
     get :deny_invite
     get :sent_invite
     get :set_preferences
     get :recommended_profiles
     get :prefered_profiles
     get :recent_profiles
     get :premimum_profiles
     get :get_area
     get :profile_search
     get :general_search
     get :shortlisted_profile
     get :upload_verfication_files
     post :upload_verfication_files
     get :set_privacy_option
     get :set_hobby_music
     get :set_package
     get :client_feedback
     get :additional_profile_photos
     post :additional_profile_photos
     get :basic_search



     
     end   
   end
   resources :homes do
      collection do
        get :index


        end
      end





  resources :home do
   collection do
    
     get :contact
     get :members
     get :privacy
     get :terms
     get :upgrade
     get :services
     get :about
     get :faq
     get :shortcodes
     get :index

     end   
 end
 resources :messages do
   collection do
     get :inbox
     get :sent
    
     end   
 end
  resources :authentications do
   collection do
     get :login
     get :register
     
     end   
 end
 resources :inboxes do
      collection do
          get :inbox
          get :sent_message


        end
    end

 
end

   

                 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/client_feedback.rb
class ClientFeedback < ApplicationRecord
	has_attached_file :profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/country_area.rb
class CountryArea < ApplicationRecord
end

app/models/inbox.rb
class Inbox < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/package_list.rb
class PackageList < ApplicationRecord
end

app/models/package_log.rb
class PackageLog < ApplicationRecord
end

app/models/partner_preference.rb
class PartnerPreference < ApplicationRecord
end

app/models/privacy_option.rb
class PrivacyOption < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord


	
	has_attached_file :profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/profile_hobby_list.rb
class ProfileHobbyList < ApplicationRecord
end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord

	has_attached_file :additional_profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :additional_profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/profile_invitation.rb
class ProfileInvitation < ApplicationRecord
end

app/models/religion.rb
class Religion < ApplicationRecord
end

app/models/user_feedback.rb
class UserFeedback < ApplicationRecord
end

app/models/web_profile.rb
class WebProfile < ApplicationRecord
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.fetch(:message, {})
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="grid_3">
  <div class="container">

<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>
</div>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>