config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
 
  resources :profiles do
   collection do
     get :view_profile
     get :search
     get :search_id  
     get :profile
     get :shortlisted
     get :viewed_profile
     get :register
     get :matches
     get :viewed_not_contacted
     get :create_profile
     get :add_profile_picture
     post :add_profile_picture
     get :send_accept_invite
     get :approve_invite
     get :deny_invite
     get :sent_invite
     get :set_preferences
     get :recommended_profiles
     get :prefered_profiles
     get :recent_profiles
     get :premimum_profiles
     get :get_area
     get :profile_search
     get :general_search
     get :shortlisted_profile
     get :upload_verfication_files
     post :upload_verfication_files
     get :set_privacy_option
     get :set_hobby_music
     get :set_package
     get :client_feedback
     get :additional_profile_photos
     post :additional_profile_photos
     get :basic_search



     
     end   
   end
   resources :homes do
      collection do
        get :index


        end
      end





  resources :home do
   collection do
    
     get :contact
     get :members
     get :privacy
     get :terms
     get :upgrade
     get :services
     get :about
     get :faq
     get :shortcodes
     get :index

     end   
 end
 resources :messages do
   collection do
     get :inbox
     get :sent
    
     end   
 end
  resources :authentications do
   collection do
     get :login
     get :register
     
     end   
 end
 resources :inboxes do
      collection do
          get :inbox
          get :sent_message


        end
    end

 
end

   

                 

app/models/profile.rb
class Profile < ApplicationRecord


	
	has_attached_file :profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/profiles_controller.rb
require 'date'
class ProfilesController < ApplicationController


  def basic_search

    @countries =Country.all
    @languages =Language.all
    @religions =Religion.all
    @area_countries = CountryArea.all
  ############################################################
    if  params.include?(:submit_check)

      


      #diet = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:diet).try(:first).to_s
      #education_field = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:education_field).try(:first).to_s
      age_start = profile_params[:age_start]
      #PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:age_start).try(:first).to_i
      age_end = profile_params[:age_end]
      #PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:age_end).try(:first).to_i
      #smoking_status = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:smoking_status).try(:first).to_i
      #drinking_status = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:drinking_status).try(:first).to_i
      #height_meter_start = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:height_meter_start).try(:first).to_f
      #height_meter_end = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:height_meter_end).try(:first).to_f
      #body_type = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:body_type).try(:first).to_s
      #education_level = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:education_level).try(:first).to_s
      #country_id =profile_params[:age_end]
      live_in = Country.where(:country_id =>profile_params[:country_id].to_i).limit(1).pluck(:country_name).try(:first).to_s 
      #PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:live_in).try(:first).to_s
      living_in  = profile_params[:living_in]
      #PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:living_in).try(:first).to_s
      marital_status  = profile_params[:marital_status]
      #PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:marital_status).try(:first).to_s
      #work_with  = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:work_with).try(:first).to_s
      #annual_income  = PartnerPreference.where(:profile_id => profile_id.to_i).limit(1).pluck(:annual_income).try(:first).to_f

      inch = profile_params[:height_inch_start]
      feet = profile_params[:height_feet_start]
        meter = 0
        meter = ( inch.to_f * 0.0254 )
        height_meter_start = meter + (feet.to_f * 0.3048)

        inch = profile_params[:height_inch_end]
        feet = profile_params[:height_feet_end]
        meter = 0
        meter = ( inch.to_f * 0.0254 )
        height_meter_end = meter + (feet.to_f * 0.3048)

      gender = Profile.where(:profile_id => profile_id.to_i).limit(1).pluck(:gender).try(:first).to_s
      religion = profile_params[:religion]
      #Profile.where(:profile_id => profile_id.to_i).limit(1).pluck(:religion).try(:first).to_s
      mother_tongue = profile_params[:mother_tongue]
      #Profile.where(:profile_id => profile_id.to_i).limit(1).pluck(:mother_tongue).try(:first).to_s
      if gender.to_s == "Female" 

        prefered_gender = "Female"
      else

        prefered_gender = "Male"
      end


      

        
            

        @profiles = Client.joins('INNER JOIN profiles ON clients.client_id = profiles.client_id ').where('profiles.age >= ? AND profiles.age <= ? AND profiles.height_meter >= ? AND profiles.height_meter <= ? AND profiles.live_in = ?  AND profiles.living_in = ? AND profiles.marital_status = ?  AND clients.client_status = ? AND profiles.gender = ? AND profiles.religion = ? AND profiles.mother_tongue = ?', age_start , age_end , height_meter_start , height_meter_end,  live_in,living_in, marital_status,"Active",prefered_gender,religion,mother_tongue).select("profiles.profile_id").to_a
            #puts "Profile id: " + @profiles[0].profile_id.to_s 
          

            



        


        
        list_string = ''
        array_rejected_list = Array[]

        array_primary_list = Array[]
        array_after_primary_filter_list = Array[]
        array_recommended_list =Array[]


      res = @profiles[0].profile_id.nil? rescue true
      unless res
          i = 0
          loop do

            array_primary_list.push(@profiles[i].profile_id.to_s)

              i += 1
              if i >= @profiles.length.to_i

                array_primary_list = array_primary_list.uniq
                break       # this will cause execution to exit the loop
              end
          end
      else
        array_primary_list = []


      end


        @get_rejected = ProfileRejectedList.where(:profile_id => profile_id.to_i)
      res = @get_rejected[0].profile_id.nil? rescue true
      unless res
          i = 0
          loop do

            list_string = list_string.to_s + @get_rejected[i].id_list.to_s

              i += 1
              if i >= @get_rejected.length.to_i

                array_rejected_list = list_string.split(',').uniq
                break       # this will cause execution to exit the loop
              end
          end
      else

        array_rejected_list = []

      end

      array_after_primary_filter_list = array_primary_list - array_rejected_list
      array_recommended_list = array_after_primary_filter_list = array_after_primary_filter_list.uniq.shuffle



      puts 'array_primary_list'
      puts array_primary_list.inspect
      puts 'array_rejected_list'
      puts array_rejected_list.inspect
      puts 'array_after_primary_filter_list'
      puts array_after_primary_filter_list.inspect
      @final_recommended_list =[]

      res = array_recommended_list[0].nil? rescue true
      unless res
          i = 0
          loop do
            unless array_recommended_list[i].blank?

              current_profile_id = array_recommended_list[i].to_i

              @profile_details =Profile.where(:profile_id => current_profile_id)

              

              
              # puts feet.to_s + " " + inch.to_s
              height_cm = 100 * @profile_details[i].height_meter
              number = height_cm * 0.393701
              inches = (number*10).ceil/10.0
              ft = (inches / 12).to_i
                inch = (inches % 12).to_i
                puts "LALALALALLALALALLALALALALLALALALLALALALLALALALLAUUUUUUUUUUUUU"
              puts ft.to_s + " ft " + inch.to_s  + " inch"
              final_height =  ft.to_s + " ft " + inch.to_s  + " inch"



              @priv_options = PrivacyOption.where('profile_id = ?  ', profile_id)
            #.update_all(:display_name_status => profile_params[:display_name_status] , :profile_visible_registered_status => profile_params[:profile_visible_registered_status] ,:profile_visible_all_status => profile_params[:profile_visible_all_status] ,:profile_hide_status => profile_params[:profile_hide_status] )



              @final_recommended_list << {profile_hide_status: @priv_options[0].profile_hide_status ,profile_visible_all_status: @priv_options[0].profile_visible_all_status ,profile_visible_registered_status: @priv_options[0].profile_visible_registered_status , display_name_status: @priv_options[0].display_name_status , number_of_children: @profile_details[i].number_of_children ,marital_status: @profile_details[i].marital_status ,live_in: @profile_details[i].live_in ,disability: @profile_details[i].disability ,about_myself: @profile_details[i].about_myself ,annual_income: @profile_details[i].annual_income ,work_as: @profile_details[i].work_as ,work_with: @profile_details[i].work_with ,education_field: @profile_details[i].education_field ,education_level:@profile_details[i].education_level ,mobile_no:@profile_details[i].mobile_no ,number_of_sisters:@profile_details[i].number_of_sisters ,number_of_brothers:@profile_details[i].number_of_brothers ,mother_name:@profile_details[i].mother_name ,father_name:@profile_details[i].father_name , body_type:@profile_details[i].body_type ,drinking_status:@profile_details[i].drinking_status , smoking_status:@profile_details[i].smoking_status ,height_meter: final_height ,living_in:@profile_details[i].living_in ,other_languages:@profile_details[i].other_languages ,mother_tongue:@profile_details[i].mother_tongue ,age:@profile_details[i].age ,last_name:@profile_details[i].last_name ,first_name:@profile_details[i].first_name , profile_photo:@profile_details[i].profile_photo ,   official_id: @profile_details[i].official_id }



            end
            

              i += 1
              if i >= array_recommended_list.length.to_i
                

                break       # this will cause execution to exit the loop
              end
          end

      end
      puts "RECOMMENDED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! LIST"



      puts @final_recommended_list.inspect
      redirect_to profile_search_profiles_path

    end
    #################################################################

    
  end

  def additional_profile_photos
    cipher = Gibberish::AES.new('p4ssw0rd')
    client_id = id = cipher.decrypt(session[:client_id])
    profile_id = Profile.where(:client_id => id.to_i).limit(1).pluck(:profile_id).try(:first).to_i
      
     
    @testlist =[]

    @testlist << {image_name: "Image 2" }
    @testlist << {image_name: "Image 3" }
    @testlist << {image_name: "Image 4" }




  


    unless ProfileImage.exists?(:image_name => "Image 1" ,:profile_id => profile_id.to_i  )
      first_instance = ProfileImage.new(:image_name => "Image 1" ,:profile_id => profile_id.to_i)

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/add_profile_picture.html.erb
<%= form_for(:profiles, url: add_profile_picture_profiles_path, method: :post , :html => {:multipart => true} ) do |f| %>





<div mclass='form-group'>
	

	<label>Profile Photo</label>




	<%= f.file_field :profile_photo,class: 'form-control' %>
</div>

	<%= f.submit "Submit" , :class => "btn btn-primary pull-right "  , name: 'submit_check'%>





<% end %>

app/views/profiles/additional_profile_photos.html.erb
<%= form_for(:profiles, url: additional_profile_photos_profiles_path, method: :post , :html => {:multipart => true} ) do |f| %>

<fieldset>


        <% @testlist.each do |lists| %>
            <div class="form-group">
             
                
                  <label>Photos</label>
                  <input id="testname" name="hrhireportals[testname]"  type="text" class="form-control required" value='<%= lists[:image_name]%>' readonly>
                </div>

                 <div class="form-group">
                
                  <%= f.file_field :additional_profile_photo, name: "profiles[attachments][]" ,class: 'form-control'%>
                </div>

                <div class="form-group">


                    
            

                  <input type="hidden" name='<%= lists[:image_name] %>' value=<%= lists[:image_name]%>><%= lists[:image_name] %>



            <input type="checkbox" name="a[<%= lists[:image_name] %>][]"  id="a<%= lists[:image_name] %>" />
              <label for="a<%= lists[:image_name]%>"></label>

                  </div>
             
                
              
            

        <%end%>

      </fieldset>


  <%= f.submit "Submit" , :class => "btn btn-primary pull-right "  , name: 'submit_check'%>
<%end%>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/profile_search.html.erb
   
  

<div class="grid_3">
  <div class="container">


   <%= form_for(:profiles, url: profile_search_profiles_path, method: :get  ) do |f| %>

<div class='form-group'>
	

	<label>age start</label>




	<%= f.number_field :age_start,class: 'form-control' %>
</div>

<div class='form-group'>
	

	<label>age end</label>




	<%= f.number_field :age_end,class: 'form-control' %>
</div>





<div class='form-group'>
	

	<label>height_feet_start</label>




	<%= f.text_field :height_feet_start,class: 'form-control' %>
</div>

<div class='form-group'>
	

	<label>height_inch_start</label>




	<%= f.text_field :height_inch_start,class: 'form-control' %>
</div>




<div class='form-group'>
	

	<label>height_feet_end</label>




	<%= f.text_field :height_feet_end,class: 'form-control' %>
</div>

<div class='form-group'>
	

	<label>height_inch_end</label>




	<%= f.text_field :height_inch_end,class: 'form-control' %>
</div>







<div class='form-group'>
	

<label>Mother Tongue</label>




	    <%= f.select :mother_tongue, options_for_select(@languages.collect{|bp| [bp.language_name, bp.language_name]}) %>
</div>








<div class='form-group'>
	

<label>Religion</label>





	 <%= f.select :religion, options_for_select(@religions.collect{|bp| [bp.religion_name, bp.religion_name]}) %>
</div>




<div class='form-group'>
	
<label>live_in(Country)</label>


      <%= f.select :country_id, options_for_select(@countries.collect{|bp| [bp.country_name, bp.country_id]}) %>
     
</div>

<div class='form-group'>


<div class='form-group'>
	

	<label>living_in(Area)</label>




   <%= f.select :area_name, options_for_select(@area_countries.collect{|l| [l.area_name, l.area_name]}), {}, {"data-option-dependent" => true, "data-option-observed" => "profiles_country_id","data-option-url"  => "/profiles/get_area.json?country_id=:profiles_country_id", "data-option-key-method"  => :area_name, "data-option-value-method" => :area_name, 
      "data-option-key-method" => :area_name, "data-option-value-method" => :area_name,
 } %>
</div>
	

<label>marital_status</label>




	<%= f.text_field :marital_status,class: 'form-control' %>
</div>

















	<%= f.submit "Search" , :class => "btn btn-primary pull-right "  , name: 'submit_check'%>





<% end %>


</div>
</div>

app/views/profiles/shortlisted.html.erb

<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.html"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Shortlisted Profile</li>
     </ul>
   </div>
   <div class="col-md-3 col_5">
   	 <ul class="match_box">
   	 	<h4>Matches</h4>
   	 	<li><a href="#">Mutual Matches</a></li>
   	 	<li><a href="#">Profiles yet to be viewed</a></li>
   	 	<li><a href="#">Mutual Matches</a></li>
   	 </ul>
     <ul class="menu">
		<li class="item1"><h3 class="m_2">Show Profiles Created</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">within a week (2) </a></li>
			<li class="subitem2"><a href="#">within a month (4)</a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Profile type</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">with Photo (3) </a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Marital Status</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Unmarried (2) </a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Mother Tongue</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">English </a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Education</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Bachelors-Engineering </a></li>
			<li class="subitem1"><a href="#">Masters-Engineering </a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Occupation</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Engineer-Non IT (2) </a></li>
			<li class="subitem1"><a href="#">Software Professional (3)</a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Physical Status</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Normal (2) </a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Eating Habits</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Non Vegetarian (3)</a></li>
			<li class="subitem1"><a href="#">Vegetarian (2)</a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Smoking</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Not Specified (3)</a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Drinking</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Not Specified (3)</a></li>
			<li class="subitem1"><a href="#">Never Drinks (3)</a></li>
		  </ul>
		</li>
		<li class="item1"><h3 class="m_2">Profile Created by</h3>
		  <ul class="cute">
			<li class="subitem1"><a href="#">Self (1)</a></li>
		  </ul>
		</li>
	  </ul>
   </div>
   <div class="col-md-9 members_box">
       <div class="terms">
		 <h2>Shortlisted Profile</h2>
		  <div class="terms_top">
			<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.</p>
			<ol class="terms_list">
				<li>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum".</li>
				<li>Lusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati.</li>
				<li>Praesentium voluptatum deleniti atque corrupti quos</li>
				<li>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi.</li>
				<li>Mentum eleifend enim a feugiat distinctio lor</li>
			</ol>
			<h4>There are many variations of passages</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Integer sed arcu. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non <a href="#">libero consectetur adipiscing</a> elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque viverra vehicula sem ut volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat.</p>
			<p><strong>Iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non sit amet, consectetur adipiscing elit. Ut adipiscing elit magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat. Pellentesque lorem ipsum dolor sit amet. Ut non libero magna. Sed et quam lacus. Fusce condimentum eleifend enim a feugiat <a href="#">consectetur adipiscing elit</a>.</strong></p>
		  </div> 	
	   </div>
    </div>
   <div class="clearfix"> </div>
  </div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/upload_verfication_files.html.erb
<%= form_for(:profiles, url: upload_verfication_files_profiles_path, method: :post , :html => {:multipart => true} ) do |f| %>

<fieldset>


        <% @testlist.each do |lists| %>
            <div class="form-group">
             
                
                  <label>Attachments</label>
                  <input id="testname" name="hrhireportals[testname]"  type="text" class="form-control required" value='<%= lists[:doc_name]%>' readonly>
                </div>

                 <div class="form-group">
                
                  <%= f.file_field :attach_trust, name: "profiles[attachments][]" ,class: 'form-control'  %>
                </div>
                 <div class="form-group">


                     <input type="hidden" name="course2[track_codes2][]"  value = "<%= lists[:doc_name] %>" >
                </div>

                 <div class="form-group">


                    
            

                  <input type="hidden" name='<%= lists[:doc_name] %>' value=<%= lists[:doc_name]%>><%= lists[:doc_name] %>



            <input type="checkbox" name="a[<%= lists[:doc_name] %>][]"  id="a<%= lists[:doc_name] %>" />
              <label for="a<%= lists[:doc_name]%>"></label>

                  </div>



                
              
            

        <%end%>

      </fieldset>


  <%= f.submit "Submit" , :class => "btn btn-primary pull-right "  , name: 'submit_check'%>
<%end%>