config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
 
  resources :profiles do
   collection do
     get :view_profile
     get :search
     get :search_id  
     get :profile
     get :shortlisted
     get :viewed_profile
     get :register
     get :matches
     get :viewed_not_contacted
     get :create_profile
     get :add_profile_picture
     post :add_profile_picture
     get :send_accept_invite
     get :approve_invite
     get :deny_invite
     get :sent_invite
     get :set_preferences
     get :recommended_profiles
     get :prefered_profiles
     get :recent_profiles
     get :premimum_profiles
     get :get_area
     get :profile_search
     get :general_search
     get :shortlisted_profile
     get :upload_verfication_files
     post :upload_verfication_files
     get :set_privacy_option
     get :set_hobby_music
     get :set_package
     get :client_feedback
     get :additional_profile_photos
     post :additional_profile_photos
     get :basic_search



     
     end   
   end
   resources :homes do
      collection do
        get :index


        end
      end





  resources :home do
   collection do
    
     get :contact
     get :members
     get :privacy
     get :terms
     get :upgrade
     get :services
     get :about
     get :faq
     get :shortcodes
     get :index

     end   
 end
 resources :messages do
   collection do
     get :inbox
     get :sent
    
     end   
 end
  resources :authentications do
   collection do
     get :login
     get :register
     
     end   
 end
 resources :inboxes do
      collection do
          get :inbox
          get :sent_message


        end
    end

 
end

   

                 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/client_feedback.rb
class ClientFeedback < ApplicationRecord
	has_attached_file :profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

	
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/country_area.rb
class CountryArea < ApplicationRecord
end

app/models/inbox.rb
class Inbox < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/package_list.rb
class PackageList < ApplicationRecord
end

app/models/package_log.rb
class PackageLog < ApplicationRecord
end

app/models/partner_preference.rb
class PartnerPreference < ApplicationRecord
end

app/models/privacy_option.rb
class PrivacyOption < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord


	
	has_attached_file :profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/profile_hobby_list.rb
class ProfileHobbyList < ApplicationRecord
end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord

	has_attached_file :additional_profile_photo,
   	:default_url => "noprofile_big.png"



   #, :styles => { :small => "160x160>" }
  	validates_attachment :additional_profile_photo, 
    :file_size => {:maximum => 6.5.megabytes.to_i } ,content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/profile_invitation.rb
class ProfileInvitation < ApplicationRecord
end

app/models/religion.rb
class Religion < ApplicationRecord
end

app/models/user_feedback.rb
class UserFeedback < ApplicationRecord
end

app/models/web_profile.rb
class WebProfile < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
    @countries =Country.all
    @languages =Language.all
    @religions =Religion.all
    @area_countries = CountryArea.all
  end
	
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index

  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      
      params.require(:homes).permit!
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/about.html.erb

<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.html"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">About</li>
     </ul>
   </div>
   <div class="about">
   	  <div class="col-md-6 about_left">
   	 
   	  	<%=image_tag("a3.jpg", class: ' img-responsive' )%>
   	  </div>
   	  <div class="col-md-6 about_right">
   	  	<h1>About us</h1>
   	  	<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
   	  	<div class="accordation">
		   <div class="jb-accordion-wrapper">
				<div class="jb-accordion-title">Accordion 1 <button type="button" class="jb-accordion-button" data-toggle="collapse" data-target="#accordion-1-"><i class="fa fa-angle-down"> </i></button></div>
				<p><!-- /.accordion-title -->
				</p><div id="accordion-1-" class="jb-accordion-content collapse in" style="height: auto;">
				<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae...</p>
				</div>
				<p><!-- /.collapse --></p>
			</div>
			<div class="jb-accordion-wrapper">
				<div class="jb-accordion-title">Accordion2 <button type="button" class="jb-accordion-button" data-toggle="collapse" data-target="#accordion2-"><i class="fa fa-angle-down"> </i></button></div>
				<p><!-- /.accordion-title -->
				</p><div id="accordion2-" class="jb-accordion-content collapse ">
				<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt </p>
				</div>
				<p><!-- /.collapse --></p>
			</div>
			<div class="jb-accordion-wrapper">
				<div class="jb-accordion-title">Accordion3<button type="button" class="jb-accordion-button" data-toggle="collapse" data-target="#accordion3"><i class="fa fa-angle-down"> </i></button></div>
				<p><!-- /.accordion-title -->
				</p><div id="accordion3" class="jb-accordion-content collapse ">
				<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt </p>
				</div>
				<p><!-- /.collapse --></p>
			</div>
		</div>
   	  </div>
   	  <div class="clearfix"> </div>
   </div>
  </div>
</div>
<div class="about_middle">
	<div class="container">
	  <h2>Happy Clients</h2>
	  <div class="about_middle-grid1">
		<div class="col-sm-6 testi_grid list-item-0">
			<blockquote class="testi_grid_blockquote">
				<figure class="featured-thumbnail">
				
					<%=image_tag("a1.jpg", class: ' img-responsive' )%>					
				</figure>
				<div><a href="#">Aenean nonummy hendrerit mau phasellu porta. Fusce suscipit varius mi sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui.…</a>
				<div class="clearfix"></div>
				</div>
			</blockquote>
		    <small class="testi-meta"><span class="user">Eiusmod tempor incididunt</span></small>
		</div>
		<div class="col-sm-6 testi_grid list-item-1">
			<blockquote class="testi_grid_blockquote">
				<figure class="featured-thumbnail">
	
					<%=image_tag("a2.jpg", class: ' img-responsive' )%>
				</figure>
				<div><a href="#">Aenean nonummy hendrerit mau phasellu porta. Fusce suscipit varius mi sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui.…</a>
				<div class="clearfix"></div>
				</div>
			</blockquote>
			<small class="testi-meta1"><span class="user">Sint occaecat </span></small>
		</div>
		<div class="clearfix"> </div>
	  </div>
	  <div class="about_middle-grid2">
		<div class="col-sm-6 testi_grid list-item-0">
			<blockquote class="testi_grid_blockquote">
				<figure class="featured-thumbnail">
					
					<%=image_tag("a1.jpg", class: ' img-responsive' )%>
				</figure>
				<div><a href="#">Aenean nonummy hendrerit mau phasellu porta. Fusce suscipit varius mi sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui.…</a>
				<div class="clearfix"></div>
				</div>
			</blockquote>
		    <small class="testi-meta"><span class="user">Eiusmod tempor incididunt</span></small>
		</div>
		<div class="col-sm-6 testi_grid list-item-1">
			<blockquote class="testi_grid_blockquote">
				<figure class="featured-thumbnail">
					
					<%=image_tag("a2.jpg", class: 'img-responsive' )%>
				</figure>
				<div><a href="#">Aenean nonummy hendrerit mau phasellu porta. Fusce suscipit varius mi sed. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla dui.…</a>
				<div class="clearfix"></div>
				</div>
			</blockquote>
			<small class="testi-meta1"><span class="user">Sint occaecat </span></small>
		</div>
		<div class="clearfix"> </div>
	  </div>
	</div>
</div>
<div class="about_bottom">
	<div class="container">
		<h3>Team</h3>
	   <div class="col-md-3 about_grid1">
		  <ul class="posts-grid our-team">
			<li class="list-item-1">
				<figure class="thumbnail_1 thumbnail">
					<a href="#"><%=image_tag("a4.jpg", class: 'img-responsive' )%></a>
					<div class="post_networks">
						<ul>
							<li class="network_0"><a href="#" title=""><i class="fa fa-facebook"></i></a></li>
						</ul>
					</div>
			    </figure>
			    <div class="desc">
			    	<h4><a href="#">Perspiciatis</a></h4>
			    	<p>Lorem ipsum dolor sit amet,</p>
			    </div>
			 </li>
	       </ul>
	   </div>
	   <div class="col-md-3 about_grid1">
		  <ul class="posts-grid our-team">
			<li class="list-item-1">
				<figure class="thumbnail_1 thumbnail">
					<a href="#"><%=image_tag("a5.jpg", class: 'img-responsive' )%></a>
					<div class="post_networks">
						<ul>
							<li class="network_0"><a href="#" title=""><i class="fa fa-facebook"></i></a></li>
						</ul>
					</div>
			    </figure>
			    <div class="desc">
			    	<h4><a href="#">Aspernatur </a></h4>
			    	<p>Lorem ipsum dolor sit amet,</p>
			    </div>
			 </li>
	       </ul>
	   </div>
	   <div class="col-md-3 about_grid1">
		  <ul class="posts-grid our-team">
			<li class="list-item-1">
				<figure class="thumbnail_1 thumbnail">
					<a href="#"><%=image_tag("a6.jpg", class: 'img-responsive' )%></a>
					<div class="post_networks">
						<ul>
							<li class="network_0"><a href="#" title=""><i class="fa fa-facebook"></i></a></li>
						</ul>
					</div>
			    </figure>
			    <div class="desc">
			    	<h4><a href="#">Temporibus</a></h4>
			    	<p>Lorem ipsum dolor sit amet,</p>
			    </div>
			 </li>
	       </ul>
	   </div>
	   <div class="col-md-3 about_grid1">
		  <ul class="posts-grid our-team">
			<li class="list-item-1">
				<figure class="thumbnail_1 thumbnail">
					<a href="#"><%=image_tag("a7.jpg", class: 'img-responsive' )%></a>
					<div class="post_networks">
						<ul>
							<li class="network_0"><a href="#" title=""><i class="fa fa-facebook"></i></a></li>
						</ul>
					</div>
			    </figure>
			    <div class="desc">
			    	<h4><a href="#">Serferendis</a></h4>
			    	<p>Lorem ipsum dolor sit amet,</p>
			    </div>
			 </li>
	       </ul>
	   </div>
	   <div class="clearfix"> </div>
	</div>
</div>

app/views/home/contact.html.erb

<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.html"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Contact</li>
     </ul>
   </div>
   <div class="grid_5">
      <p>Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus porta. Fusce suscipit varius mi. Cum sociis natoque penatibus et magnis dis parturient. montes, nascetur ridiculus mus. Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor, dapibus eget, elementum vel, cursus eleifend, elit.</p>
      <address class="addr row">
        <dl class="grid_4">
            <dt>Address :</dt>
            <dd>
                8901 Nulla Pariatur, <br>
                Ipsum, D05 87GR.
            </dd>
        </dl>
        <dl class="grid_4">
            <dt>Telephones :</dt>
            <dd>
                +1 800 245 4578 <br>
                +1 800 789 5478
            </dd>
        </dl>
        <dl class="grid_4">
            <dt>E-mail :</dt>
            <dd><a href="malito:mail@demolink.org">mail(at)Marital.com</a></dd>
        </dl>
      </address>
    </div>
   </div>
</div>
<div class="about_middle">
  <div class="container">
	 <h2>Contact Form</h2>
	  <form id="contact-form" class="contact-form">
        <fieldset>
          <input type="text" class="text" placeholder="" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
          <input type="text" class="text" placeholder="" value="Phone" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Phone';}">
          <input type="text" class="text" placeholder="" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
          <textarea value="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message</textarea>
          <input name="submit" type="submit" id="submit" value="Submit">
        </fieldset>
      </form>
  </div>
</div>

app/views/home/faq.html.erb

<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.html"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">FAQ</li>
     </ul>
   </div>
   <dl class="faq-list">
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Odio gravida atcursus neluctus a lorem. Maecenas tristiqu sters port rsen mate haslelu milsie quqn smetsre?</h4>
	</dt>
	<dd>
	<h4 class="marker1">A.</h4>
	<p class="m_4">Vestibulum ante ipsum primis in faucibus orci luctus et trices posuere cubilia Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit magnandrerit sit amet tincidunt ac viverra sed nulla. Donec porta diam eu massa. Quisque diam lorem interdum vapibus ac scelerisque vitae pede. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentese sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nullael diam. Sed in lacus ut enim adipiscing aliquet.</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Fusce feugiat malesuada odio. Morbi nunc odio gravida atcursus neluctus a lorem. Maecenas tristiqu?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Aenean auctor wisi et urna. Aliquarat volutpat. Duis ac turpis. Integer rutrum ante eu lacusVestibulum libero nisl porta vel scelerisque eget malesuada at neque. Vivamus eget nibh. Etiamcursus leo vel metus. Nulla facilisi. Aenean nec eros.</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Maecenas tristique orci ac sem. Duis ultricihre tra magnauae ab illo inventoa ster port rsen maet jhaslelu misleui portau?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida atcursus nec luctus a lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor dapibus eget elementum vel cursus eleifend elit.</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Duis ultricies pharetra magna. Donec accumsan malesuada orcinec sit amet eros. Lorem ipsum dolo?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentese sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nullael diam. Sed in lacus ut enim adipiscing aliquet. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est.</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Odio gravida atcursus neluctus a lorem. Maecenas tristiqu sters port rsen mate haslelu milsie quqn smetsre?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Vestibulum ante ipsum primis in faucibus orci luctus et trices posuere cubilia Suspendisse sollicitudin velit sed leo. Ut pharetra augue nec augue. Nam elit magnandrerit sit amet tincidunt ac viverra sed nulla. Donec porta diam eu massa. Quisque diam lorem interdum vapibus ac scelerisque vitae pede. Donec eget tellus non erat lacinia fermentum. Donec in velit vel ipsum auctorulvinar. Proin ullamcorper urna et tibulum iaculis lacinia est. Proin dictum elementum velit. Fusce euismod consequat ante. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Pellentese sed dolor. Aliquam congue fermentum nisl. Mauris accumsan nullael diam. Sed in lacus ut enim adipiscing aliquet.</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Fusce feugiat malesuada odio. Morbi nunc odio gravida atcursus neluctus a lorem. Maecenas tristiqu?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4">Aenean auctor wisi et urna. Aliquarat volutpat. Duis ac turpis. Integer rutrum ante eu lacusVestibulum libero nisl porta vel scelerisque eget malesuada at neque. Vivamus eget nibh. Etiamcursus leo vel metus. Nulla facilisi. Aenean nec eros.</p>
	</dd>
	<dt class="faq-list_h">
	<h4 class="marker">Q?</h4>
	<h4>Maecenas tristique orci ac sem. Duis ultricihre tra magnauae ab illo inventoa ster port rsen maet jhaslelu misleui portau?</h4>
	</dt>
	<dd>
	<h4 class="marker">A.</h4>
	<p class="m_4 m_5">Nulla dui. Fusce feugiat malesuada odio. Morbi nunc odio gravida atcursus nec luctus a lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra magna. Donec accumsan malesuada orci. Donec sit amet eros. Lorem ipsum dolor sit amet consectetuer adipiscing elit. Mauris fermentum dictum magna. Sed laoreet aliquam leo. Ut tellus dolor dapibus eget elementum vel cursus eleifend elit.</p>
	</dd>
   </dl>
  </div>
</div>

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<div class="grid_3">
  <div class="container">

<%= link_to "Create profile", create_profile_profiles_path %>
<br>
<%= link_to "Add profile picture",add_profile_picture_profiles_path %>

<br>
<%= link_to "Send and accept invite",send_accept_invite_profiles_path %>

<br>
<%= link_to "Set Preferences",set_preferences_profiles_path %>
<br>
<%= link_to "Recommended profiles",recommended_profiles_profiles_path %>
<br>
<%= link_to "Prefered profiles",prefered_profiles_profiles_path %>
<br>
<%= link_to "New profiles",recent_profiles_profiles_path %>
<br>
<%= link_to "Premimum profiles",premimum_profiles_profiles_path %>
<br>
<%= link_to "Profile Search",profile_search_profiles_path %>
<br>
<%= link_to "General Search",general_search_profiles_path %>
<br>
<%= link_to "Shortlisted profiles",shortlisted_profile_profiles_path %>

<br>
<%= link_to "Upload files for verification",upload_verfication_files_profiles_path %>

<br>
<%= link_to "Privacy option",set_privacy_option_profiles_path %>

<br>
<%= link_to "Set hobby & music ",set_hobby_music_profiles_path %>
<br>
<%= link_to "Set Package ",set_package_profiles_path %>
<br>
<%= link_to "Give your feedback",client_feedback_profiles_path %>
<br>
<%= link_to "Add extra profile photos",additional_profile_photos_profiles_path%>

<br>
<%= link_to "Sent Message",sent_message_inboxes_path(profile_id:"4"

) %>

<br>
<%= link_to "Inbox",inbox_inboxes_path %>
</div>
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>