config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
 
  resources :profiles do
   collection do
     get :view_profile
     get :search
     get :search_id  
     get :profile
     get :shortlisted
     get :viewed_profile
     get :register
     get :matches
     get :viewed_not_contacted
     get :create_profile
     get :add_profile_picture
     post :add_profile_picture
     get :send_accept_invite
     get :approve_invite
     get :deny_invite
     get :sent_invite
     get :set_preferences
     get :recommended_profiles
     get :prefered_profiles
     get :recent_profiles
     get :premimum_profiles
     get :get_area
     get :profile_search
     get :general_search
     get :shortlisted_profile
     get :upload_verfication_files
     post :upload_verfication_files
     get :set_privacy_option
     get :set_hobby_music
     get :set_package
     get :client_feedback
     get :additional_profile_photos
     post :additional_profile_photos
     get :basic_search



     
     end   
   end
   resources :homes do
      collection do
        get :index


        end
      end





  resources :home do
   collection do
    
     get :contact
     get :members
     get :privacy
     get :terms
     get :upgrade
     get :services
     get :about
     get :faq
     get :shortcodes
     get :index

     end   
 end
 resources :messages do
   collection do
     get :inbox
     get :sent
    
     end   
 end
  resources :authentications do
   collection do
     get :login
     get :register
     
     end   
 end
 resources :inboxes do
      collection do
          get :inbox
          get :sent_message


        end
    end

 
end

   

                 

app/models/inbox.rb
class Inbox < ApplicationRecord
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController

  def sent_message
    cipher = Gibberish::AES.new('p4ssw0rd')
    client_id = id = cipher.decrypt(session[:client_id])
    profile_id = Profile.where(:client_id => id.to_i).limit(1).pluck(:profile_id).try(:first).to_i


    
    unless params[:profile_id].blank?
      @receive_profile_id = params[:profile_id]
      
    end
    #check if the sender is allowed to sent the message to the recipient
    list_string =""

    @get_rejected = ProfileRejectedList.where(:profile_id => params[:profile_id].to_i)
    res = @get_rejected[0].profile_id.nil? rescue true
    unless res
        i = 0
        loop do

          list_string = list_string.to_s + @get_rejected[i].id_list.to_s

            i += 1
            if i >= @get_rejected.length.to_i

              array_rejected_list = list_string.split(',').uniq
              break       # this will cause execution to exit the loop
            end
        end
    else

      array_rejected_list = []

    end


    unless array_rejected_list.include? profile_id
    
      Inbox.where(:sent_profile_id =>  params[:profile_id] ,:receive_profile_id =>profile_id ).update_all(receive_message_seen: 1)

      @message_list = []

      receive_profile_first_name = Profile.where(:profile_id => params[:profile_id].to_i).limit(1).pluck(:first_name).try(:first).to_s
      receive_profile_last_name = Profile.where(:profile_id => params[:profile_id].to_i).limit(1).pluck(:last_name).try(:first).to_s
      receive_profile_official_id = Profile.where(:profile_id => params[:profile_id].to_i).limit(1).pluck(:official_id).try(:first).to_s

      @offcial_receiver_identifier = receive_profile_first_name + " " + receive_profile_last_name +"(" +receive_profile_official_id+")"


      

      @get_inbox_contains = Inbox.where(:sent_profile_id => profile_id , :receive_profile_id => params[:profile_id]).or(Inbox.where(:receive_profile_id => profile_id , :sent_profile_id => params[:profile_id]))

      resMain = @get_inbox_contains[0].id.nil? rescue true
      unless resMain
        i = 0
        loop do
          resM = @get_inbox_contains[i].id.nil? rescue true
          unless resM

            @message_list << {receive_message_seen:@get_inbox_contains[i].receive_message_seen,message:@get_inbox_contains[i].message,receive_profile_id:@get_inbox_contains[i].receive_profile_id,sent_profile_id:@get_inbox_contains[i].sent_profile_id}
          end
          i += 1
          if i >= @get_inbox_contains.length.to_i
        
            break       # this will cause execution to exit the loop
          end
        end
      end 


      puts "MESSAGE LIST"
      puts @message_list.inspect


      if  params.include?(:submit_check)

        receive_profile_id =  params["receive_profile_id"]
        unless receive_profile_id.blank?

          first_instance = Inbox.new(:receive_message_seen => 0 ,:message =>inbox_params[:message],:sent_profile_id => profile_id , :receive_profile_id => receive_profile_id)
          first_save = first_instance.save
          #redirect_to inbox_path, notice: 'Thank you!!! Hope you find your match'

        else
          
        end

        


      end
    else
      redirect_to inbox_inboxes_path, notice: 'You are not authorized to sent message to this user'

    end


    








    
  end

  def inbox
    cipher = Gibberish::AES.new('p4ssw0rd')
    client_id = id = cipher.decrypt(session[:client_id])
    profile_id = Profile.where(:client_id => id.to_i).limit(1).pluck(:profile_id).try(:first).to_i
    @message_list =[]

    @get_inbox_contains = Inbox.where(:receive_profile_id => profile_id)

    resMain = @get_inbox_contains[0].id.nil? rescue true
    unless resMain
      i = 0
      loop do
        resM = @get_inbox_contains[i].id.nil? rescue true
        unless resM
          receive_profile_first_name = Profile.where(:profile_id => @get_inbox_contains[i].sent_profile_id.to_i).limit(1).pluck(:first_name).try(:first).to_s
          receive_profile_last_name = Profile.where(:profile_id => @get_inbox_contains[i].sent_profile_id.to_i).limit(1).pluck(:last_name).try(:first).to_s
          receive_profile_official_id = Profile.where(:profile_id => @get_inbox_contains[i].sent_profile_id.to_i).limit(1).pluck(:official_id).try(:first).to_s

          offcial_receiver_identifier = receive_profile_first_name + " " + receive_profile_last_name +"(" +receive_profile_official_id+")"

          @message_list << {offcial_receiver_identifier: offcial_receiver_identifier, receive_message_seen:@get_inbox_contains[i].receive_message_seen,message:@get_inbox_contains[i].message,receive_profile_id:@get_inbox_contains[i].receive_profile_id,sent_profile_id:@get_inbox_contains[i].sent_profile_id}
        end
        i += 1
        if i >= @get_inbox_contains.length.to_i
      
          break       # this will cause execution to exit the loop
        end
      end
    end 
    puts "MESSAGE LIST"
    puts @message_list.inspect
    
  end
 

  

  private


    # Never trust parameters from the scary internet, only allow the white list through.
    def inbox_params

      params.require(:inboxes).permit!
      
    end
end

app/views/inboxes/_form.html.erb
<%= form_for(inbox) do |f| %>
  <% if inbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inbox.errors.count, "error") %> prohibited this inbox from being saved:</h2>

      <ul>
      <% inbox.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inboxes/edit.html.erb
<h1>Editing Inbox</h1>

<%= render 'form', inbox: @inbox %>

<%= link_to 'Show', @inbox %> |
<%= link_to 'Back', inboxes_path %>

app/views/inboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inboxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inboxes.each do |inbox| %>
      <tr>
        <td><%= link_to 'Show', inbox %></td>
        <td><%= link_to 'Edit', edit_inbox_path(inbox) %></td>
        <td><%= link_to 'Destroy', inbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inbox', new_inbox_path %>

app/views/inboxes/new.html.erb
<h1>New Inbox</h1>

<%= render 'form', inbox: @inbox %>

<%= link_to 'Back', inboxes_path %>

app/views/inboxes/sent_message.html.erb
 <div class="grid_3">
  <div class="container">




<%= form_for(:inboxes, url: sent_message_inboxes_path, method: :get  ) do |f| %>






<div class='form-group'>
	

	<label>Message</label>




	<%= f.text_area :message,class: 'form-control' %>
</div>
<div class='form-group'>

 <input type="hidden" name="receive_profile_id"  value = "<%= @receive_profile_id %>" 
</div>


	<%= f.submit "Submit" , :class => "btn btn-primary pull-right "  , name: 'submit_check'%>

    










	





<% end %>


</div>
</div>

app/views/inboxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inbox_path(@inbox) %> |
<%= link_to 'Back', inboxes_path %>